const CONSTANTS = {
  URLS: {
    BASE_URL: 'https://react-goodie.herokuapp.com',
  },
  TOKEN:
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxOTE4MTc2Yy05ZmRmLTQ1ZTktOWM2NC1lNzYwNjc4N2EyN2QiLCJsb2dpbiI6InVzZXIwMDEiLCJpYXQiOjE2NTI3NTI4OTF9.w2E27F-1HxgqHeGppNHNO1cXWSvsxZD69HAxcfjrjL0',
  TOKEN_INSPIRATION_TIME: 86400,
  ANIMATION_OFFSET: 200,
  ANIMATION_DURATION: 1000,
  HEADER: {
    STICKY_HEIGHT: 60,
    NOT_STICKY_HEIGHT: 61,
  },
};

export default CONSTANTS;
